debug:
  false
logging:
  level:
    org.springframework: INFO
    indi.baojie: DEBUG
# Servlet容器配置
server:
  port: 8081
  session-timeout: 7200
  tomcat:
    uri-encoding: UTF-8
  context-path: /ssa

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ssa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 1000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1

  thymeleaf:
    mode: LEGACYHTML5
    cache: false

  aop:
    # true为使用CGLIB代理，false为JDK代理，默认为false
    proxy-target-class: true
custom:
  datasource:
    size: 2
    names: ds1,ds2
    ds1:
      url: jdbc:mysql://localhost:3306/ssa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    ds2:
      url: jdbc:mysql://localhost:3306/ssa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver