spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ssa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql

  mvc:
    #视图解析配置
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  type-aliases-package: indi.baojie.demo.supervision.domain
  mapperLocations: classpath:indi/baojie/demo/supervision/dao/mapping/*.xml


#servlet容器配置
server:
  port: 80
  session-timeout: 7200
  context-path: /sup