# Servlet容器配置
server:
  port: 80
  session-timeout: 7200
  context-path: /sup

#  servlet-path: /service/*

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ssa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql

  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 1000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1

  mvc:
    # 视图解析配置
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  devtools:
    restart:
      exclude: WEB-INF/views/**

mybatis:
  type-aliases-package: indi.baojie.demo.supervision.domain
  mapperLocations: classpath:indi/baojie/demo/supervision/dao/mapping/*.xml
  configuration:
    lazy-loading-enabled: false

debug: false